import type { Metadata } from "next";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeScript } from "../components/theme-script";
import localFont from "next/font/local";
import Footer from "@/components/Footer";
import AnimatedCursor from "@/components/AnimatedCursor";
import TransitionLayout from "./TransitionLayout";
import FaceCanvas from "@/components/Character/FaceCanvas";
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
});

const monument = localFont({
  src: "../../public/fonts/MonumentExtended-Regular.otf",
  variable: "--font-monument",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeScript />
      </head>
      <ThemeProvider>
        <TransitionLayout>
          <body
            className={`${spaceGrotesk.className} ${monument.variable} bg-light dark:bg-dark`}
          >
            <Navbar />
            {children}
            <Footer />
            <AnimatedCursor />
          </body>
        </TransitionLayout>
      </ThemeProvider>
    </html>
  );
}
